extent.reporter.spark.start=true
extent.reporter.spark.out=Report/ExtentReport.html

screenshot.dir=Report/screenshots/
screenshot.rel.path=./screenshots/

basefolder.name=Report
basefolder.datetimepattern=yyyy-MM-dd_HH-mm-ss